app.name=ftp-module
ftp.temp.server=${FTP_SERVER_TEMP}
ftp.temp.port=${FTP_PORT_TEMP}
ftp.temp.user=${FTP_USER_TEMP}
ftp.temp.password=${FTP_PASSWORD_TEMP}

ftp.server=${FTP_SERVER}
ftp.port=${FTP_PORT}
ftp.user=${FTP_USER}
ftp.password=${FTP_PASSWORD}